### ISSUE TITLE
Текст из "общей картины"

### ISSUE THREAD

**Issue by ghost** [MisterBearclaw/million_bot#1]
Я бы его поправил чуток:
__________________________________________________
Сейчас в системе зарегистрировано N1. Это P1% от <число жителей РФ*0.04, у нас ведь оно есть? можно его сделать обновляемым?>  (последнее число равно 4% от числа жителей РФ). 
Из этих людей N2 привели вы и те, кого вы пригласили. 
В вашем городе зарегистрировано N3, это P2% <число жителей города*0.04> (последнее число равно 4% от числа жителей вашего города).

Заходите снова в следующую пятницу  05.06.2022, а пока не забудьте удалить этот чат!
 
<в зависимости о того, розданы ли приглашения, если мы конечно можем реализовать такое условие. Если вдруг нет, то только первый вариант>
Если вы еще не использовали свои приглашения, пожалуйста пригласите друзей! / Вы уже использовали оба ваших приглашения. Ура!
___________________________________________________

(вот так: с абзацами и с датой в европейском формате)

**Comment by MillionSerj** [comment]
Если это возможно, хорошо бы вообще выдавать два разных текста в зависимости от того, закрыты ли приглашения. Если закрыты:
________________________________________
Сейчас в системе зарегистрировано 14. Это 0.00% от 5 миллионов. Из этих людей 0 привели вы и те, кого вы пригласили. Из них 2 -- в вашем городе.

Вы уже использовали оба ваших приглашения. Ура!

Заходите снова в следующую пятницу 05.06.2022, а пока не забудьте удалить чат со мной!
__________________________________________
Если не закрыты:
________________________________________
Сейчас в системе зарегистрировано 14. Это 0.00% от 5 миллионов. Из этих людей 0 привели вы и те, кого вы пригласили. Из них 2 -- в вашем городе.

Если вы еще не использовали свои приглашения, пожалуйста пригласите друзей!

Заходите снова в следующую пятницу 05.06.2022, а пока не забудьте удалить чат со мной!
__________________________________________

Во втором тексте мы не обнаруживаем, что знаем точно, что человек не привел людей, чтобы не триггерить чувство вины.

**Comment by MillionSerj** [comment]
Если это возможно, хорошо бы вообще выдавать два разных текста в зависимости от того, закрыты ли приглашения. Если закрыты:
___________________________________________
Сейчас в системе зарегистрировано _. Из этих людей _ привели вы и те, кого вы пригласили. 
В вашем городе зарегистрировано _. Это _% от населения вашего города.
Всего в системе _ городов, где зарегистрировано не менее 4% населения. Всего в таких городах зарегистрировано _ человек. Это _% от населения России.

Вы уже использовали оба ваших приглашения. Ура!

Заходите снова в следующую пятницу 05.06.2022, а пока не забудьте удалить чат со мной!
___________________________________________

Если не закрыты:

Сейчас в системе зарегистрировано _. Из этих людей _ привели вы и те, кого вы пригласили. 
В вашем городе зарегистрировано _. Это _% от населения вашего города.
Всего в системе _ городов, где зарегистрировано не менее 4% населения. Всего в таких городах зарегистрировано _ человек. Это _% от населения России.

Если вы еще не использовали свои приглашения, пожалуйста пригласите друзей! Не приглашайте тех, кому не доверяете полностью!

Заходите снова в следующую пятницу 05.06.2022, а пока не забудьте удалить чат со мной!

**Comment by million-project-srj** [comment]
Принимаются предложения, как то же самое сформулировать лучше
