### ISSUE TITLE
Текст про пароль

### ISSUE THREAD

**Issue by ghost** [MisterBearclaw/million_bot#10]
Текст "Введите пароль" при регистрации нужно дополнить так:

"Придумайте пароль.Пожалуйста, запишите его, на бумажку и спрячьте ее в укромное место."

**Comment by MrBraveMartin** [comment]
Я бы сделал еще серьезнее.

"Придумайте пароль. Пожалуйста, запишите его, на бумажку и спрячьте ее в укромное место. Серьезно! Восстановить пароль потом будет невозможно. Это нужно в целях безопасности."
