### ISSUE TITLE
Удаление аккаунта

### ISSUE THREAD

**Issue by MrBraveMartin** [MisterBearclaw/million_bot#27]
При удалении аккаунта пригласившему "возвращается" его инвайт айди. Думаю, будет хорошо ему об этом написать, чтобы он понял, что ему надо следующего человека искать. А то он может думать, что он такой классный и оба свои инвайта уже закрыл и может расслабиться, ан нет. 

"К сожалению, один из людей, которых Вы пригласили, удалил свой аккаунт, либо его аккаунт был удален из-за неучастия в Виртуальной репетиции. Из-за этого ваше приглашение можно использовать снова. Прошу вас найти еще одного человека среди ваших друзей, родственников и знакомых и пригласить его зарегестрироваться."

**Comment by MisterBearclaw** [comment]
Увы, так нельзя делать. Иначе можно иметь неограниченные инвайты. Создаёшь аккаунт. Приглашаешь двух сержантов. Удаляешь. Это освобождает изначальные инвайт. Создаёшь новый аккаунт, приглашаешь еще двух сержантов. Повторять за казёный счёт пока сержанты не кончатся.

**Comment by million-project-srj** [comment]
Я чего-то не очень понял. Кажется, что количество сержантов в такой схеме не растет. Т.е. не растет больше, чем и без этой функции может.
