### ISSUE TITLE
Кнопка "Наши требования" при регистрации

### ISSUE THREAD

**Issue by million-project-srj** [MisterBearclaw/million_bot#30]
Убрать кнопку "Наши требования", появляющуюся после согласна - не согласна во втором вопросе регистрации.

Мы только что перед этим спрашивали людей, понимают ли они политические требования.

**Comment by MisterBearclaw** [comment]
Поэтому кнопку я не убрал, а добавил в первое - там она нужнее - нефиг спрашивать про политические требования не указав их:)
